enum ErrorMessageEnum {
  INVALID_PHONE = 'INVALID_PHONE',
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  AUTH_CODE_EXPIRED = 'AUTH_CODE_EXPIRED',
  AUTH_WRONG_CODE = 'AUTH_WRONG_CODE',
  UNKNOWN = 'UNKNOWN',
  REMOVE_NO_EFFECT = 'REMOVE_NO_EFFECT',
}

export default ErrorMessageEnum;
